// flow-typed signature: 93bebef7b960105b2d0372f6d8ec5ef6
// flow-typed version: <<STUB>>/babel-preset-env_v0.0.6/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-env/data/pluginFeatures' {
  declare module.exports: any;
}

declare module 'babel-preset-env/lib/index' {
  declare module.exports: any;
}

declare module 'babel-preset-env/lib/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-env/data/pluginFeatures.js' {
  declare module.exports: $Exports<'babel-preset-env/data/pluginFeatures'>;
}
declare module 'babel-preset-env/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-env/lib/index'>;
}
declare module 'babel-preset-env/lib/plugins.js' {
  declare module.exports: $Exports<'babel-preset-env/lib/plugins'>;
}
