// flow-typed signature: 5caab1d525750018fb0dc235de1b8ace
// flow-typed version: <<STUB>>/extract-zip_v^1.5.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-zip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-zip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-zip/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-zip/cli.js' {
  declare module.exports: $Exports<'extract-zip/cli'>;
}
declare module 'extract-zip/index' {
  declare module.exports: $Exports<'extract-zip'>;
}
declare module 'extract-zip/index.js' {
  declare module.exports: $Exports<'extract-zip'>;
}
