// flow-typed signature: fb05468eef97c1801ecfecf92ed54d4e
// flow-typed version: <<STUB>>/image-diff_v^1.6.3/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'image-diff/docs/example' {
  declare module.exports: any;
}

declare module 'image-diff/Gruntfile' {
  declare module.exports: any;
}

declare module 'image-diff/lib/image-diff' {
  declare module.exports: any;
}

declare module 'image-diff/test/extract-total-difference_test' {
  declare module.exports: any;
}

declare module 'image-diff/test/image-diff_test' {
  declare module.exports: any;
}

declare module 'image-diff/test/image-diff-get-full-result_test' {
  declare module.exports: any;
}

declare module 'image-diff/test/image-diff-get-raw-result_test' {
  declare module.exports: any;
}

declare module 'image-diff/test/utils/image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'image-diff/docs/example.js' {
  declare module.exports: $Exports<'image-diff/docs/example'>;
}
declare module 'image-diff/Gruntfile.js' {
  declare module.exports: $Exports<'image-diff/Gruntfile'>;
}
declare module 'image-diff/lib/image-diff.js' {
  declare module.exports: $Exports<'image-diff/lib/image-diff'>;
}
declare module 'image-diff/test/extract-total-difference_test.js' {
  declare module.exports: $Exports<'image-diff/test/extract-total-difference_test'>;
}
declare module 'image-diff/test/image-diff_test.js' {
  declare module.exports: $Exports<'image-diff/test/image-diff_test'>;
}
declare module 'image-diff/test/image-diff-get-full-result_test.js' {
  declare module.exports: $Exports<'image-diff/test/image-diff-get-full-result_test'>;
}
declare module 'image-diff/test/image-diff-get-raw-result_test.js' {
  declare module.exports: $Exports<'image-diff/test/image-diff-get-raw-result_test'>;
}
declare module 'image-diff/test/utils/image.js' {
  declare module.exports: $Exports<'image-diff/test/utils/image'>;
}
