// flow-typed signature: 6c8636a18cdec3f2c31f2dd29f7d2c1a
// flow-typed version: <<STUB>>/ionicons-temp_v^2.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons-temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons-temp' {
  declare module.exports: any;
}
