// flow-typed signature: ba39e1b850e33c4d998c13e86f200a89
// flow-typed version: <<STUB>>/ionicons-temp_v^2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons-temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons-temp' {
  declare module.exports: any;
}
