// flow-typed signature: 15f4e654eca2a3a3e9fa16943852cf35
// flow-typed version: <<STUB>>/ionicons-temp_v^2.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons-temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons-temp' {
  declare module.exports: any;
}
