// flow-typed signature: bea2730e2ade478f27e31905482adce4
// flow-typed version: <<STUB>>/kat-shows_v0.0.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kat-shows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kat-shows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kat-shows/browser' {
  declare module.exports: any;
}

declare module 'kat-shows/lib/kat-shows' {
  declare module.exports: any;
}

declare module 'kat-shows/lib/Torrent' {
  declare module.exports: any;
}

declare module 'kat-shows/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kat-shows/browser.js' {
  declare module.exports: $Exports<'kat-shows/browser'>;
}
declare module 'kat-shows/index' {
  declare module.exports: $Exports<'kat-shows'>;
}
declare module 'kat-shows/index.js' {
  declare module.exports: $Exports<'kat-shows'>;
}
declare module 'kat-shows/lib/kat-shows.js' {
  declare module.exports: $Exports<'kat-shows/lib/kat-shows'>;
}
declare module 'kat-shows/lib/Torrent.js' {
  declare module.exports: $Exports<'kat-shows/lib/Torrent'>;
}
declare module 'kat-shows/webpack.config.js' {
  declare module.exports: $Exports<'kat-shows/webpack.config'>;
}
