// flow-typed signature: 94cf9df49d3263081fb495e7ce880f5f
// flow-typed version: <<STUB>>/network-address_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'network-address'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'network-address' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'network-address/cli' {
  declare module.exports: any;
}

declare module 'network-address/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'network-address/cli.js' {
  declare module.exports: $Exports<'network-address/cli'>;
}
declare module 'network-address/index' {
  declare module.exports: $Exports<'network-address'>;
}
declare module 'network-address/index.js' {
  declare module.exports: $Exports<'network-address'>;
}
declare module 'network-address/test.js' {
  declare module.exports: $Exports<'network-address/test'>;
}
