// flow-typed signature: e24bf6779019e55b0d08a20090207072
// flow-typed version: <<STUB>>/notie_v^3.9.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'notie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notie/dist/notie.min' {
  declare module.exports: any;
}

declare module 'notie/gulpfile' {
  declare module.exports: any;
}

declare module 'notie/src/notie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notie/dist/notie.min.js' {
  declare module.exports: $Exports<'notie/dist/notie.min'>;
}
declare module 'notie/gulpfile.js' {
  declare module.exports: $Exports<'notie/gulpfile'>;
}
declare module 'notie/src/notie.js' {
  declare module.exports: $Exports<'notie/src/notie'>;
}
