// flow-typed signature: 4ad502ad364db39881f77832263c4ac4
// flow-typed version: <<STUB>>/opensubtitles-api_v^3.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opensubtitles-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'opensubtitles-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opensubtitles-api/lib/hash' {
  declare module.exports: any;
}

declare module 'opensubtitles-api/lib/identify' {
  declare module.exports: any;
}

declare module 'opensubtitles-api/lib/opensubtitles' {
  declare module.exports: any;
}

declare module 'opensubtitles-api/lib/search' {
  declare module.exports: any;
}

declare module 'opensubtitles-api/lib/upload' {
  declare module.exports: any;
}

declare module 'opensubtitles-api/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opensubtitles-api/index' {
  declare module.exports: $Exports<'opensubtitles-api'>;
}
declare module 'opensubtitles-api/index.js' {
  declare module.exports: $Exports<'opensubtitles-api'>;
}
declare module 'opensubtitles-api/lib/hash.js' {
  declare module.exports: $Exports<'opensubtitles-api/lib/hash'>;
}
declare module 'opensubtitles-api/lib/identify.js' {
  declare module.exports: $Exports<'opensubtitles-api/lib/identify'>;
}
declare module 'opensubtitles-api/lib/opensubtitles.js' {
  declare module.exports: $Exports<'opensubtitles-api/lib/opensubtitles'>;
}
declare module 'opensubtitles-api/lib/search.js' {
  declare module.exports: $Exports<'opensubtitles-api/lib/search'>;
}
declare module 'opensubtitles-api/lib/upload.js' {
  declare module.exports: $Exports<'opensubtitles-api/lib/upload'>;
}
declare module 'opensubtitles-api/tests.js' {
  declare module.exports: $Exports<'opensubtitles-api/tests'>;
}
