// flow-typed signature: 91e5129f29e37e040d92acc46086ebf0
// flow-typed version: <<STUB>>/optimize-js_v^1.0.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optimize-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'optimize-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optimize-js/lib/bin' {
  declare module.exports: any;
}

declare module 'optimize-js/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optimize-js/lib/bin.js' {
  declare module.exports: $Exports<'optimize-js/lib/bin'>;
}
declare module 'optimize-js/lib/index.js' {
  declare module.exports: $Exports<'optimize-js/lib/index'>;
}
