// flow-typed signature: 20b1e6a22886fb3dc787c7b3c802d52d
// flow-typed version: <<STUB>>/plyr_v^2.0.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plyr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'plyr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plyr/demo/dist/demo' {
  declare module.exports: any;
}

declare module 'plyr/demo/src/js/lib/classlist' {
  declare module.exports: any;
}

declare module 'plyr/demo/src/js/main' {
  declare module.exports: any;
}

declare module 'plyr/dist/plyr' {
  declare module.exports: any;
}

declare module 'plyr/gulpfile' {
  declare module.exports: any;
}

declare module 'plyr/src/js/plyr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plyr/demo/dist/demo.js' {
  declare module.exports: $Exports<'plyr/demo/dist/demo'>;
}
declare module 'plyr/demo/src/js/lib/classlist.js' {
  declare module.exports: $Exports<'plyr/demo/src/js/lib/classlist'>;
}
declare module 'plyr/demo/src/js/main.js' {
  declare module.exports: $Exports<'plyr/demo/src/js/main'>;
}
declare module 'plyr/dist/plyr.js' {
  declare module.exports: $Exports<'plyr/dist/plyr'>;
}
declare module 'plyr/gulpfile.js' {
  declare module.exports: $Exports<'plyr/gulpfile'>;
}
declare module 'plyr/src/js/plyr.js' {
  declare module.exports: $Exports<'plyr/src/js/plyr'>;
}
