// flow-typed signature: 50de1b219707153d7b2b3804d9eef5fb
// flow-typed version: <<STUB>>/rndm_v^1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rndm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rndm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rndm/index' {
  declare module.exports: $Exports<'rndm'>;
}
declare module 'rndm/index.js' {
  declare module.exports: $Exports<'rndm'>;
}
