// flow-typed signature: a2771d22007e0a17d7d02f96dbd3692b
// flow-typed version: <<STUB>>/speedtest-net_v^1.2.8/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'speedtest-net'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'speedtest-net' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'speedtest-net/index' {
  declare module.exports: $Exports<'speedtest-net'>;
}
declare module 'speedtest-net/index.js' {
  declare module.exports: $Exports<'speedtest-net'>;
}
