// flow-typed signature: 1dec3bdb9b4d5eb6a848bb78f67aefd4
// flow-typed version: <<STUB>>/srt2vtt_v^1.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'srt2vtt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'srt2vtt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'srt2vtt/bin/convert' {
  declare module.exports: any;
}

declare module 'srt2vtt/encoding' {
  declare module.exports: any;
}

declare module 'srt2vtt/reader' {
  declare module.exports: any;
}

declare module 'srt2vtt/test' {
  declare module.exports: any;
}

declare module 'srt2vtt/test/srt2vtt.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'srt2vtt/bin/convert.js' {
  declare module.exports: $Exports<'srt2vtt/bin/convert'>;
}
declare module 'srt2vtt/encoding.js' {
  declare module.exports: $Exports<'srt2vtt/encoding'>;
}
declare module 'srt2vtt/index' {
  declare module.exports: $Exports<'srt2vtt'>;
}
declare module 'srt2vtt/index.js' {
  declare module.exports: $Exports<'srt2vtt'>;
}
declare module 'srt2vtt/reader.js' {
  declare module.exports: $Exports<'srt2vtt/reader'>;
}
declare module 'srt2vtt/test.js' {
  declare module.exports: $Exports<'srt2vtt/test'>;
}
declare module 'srt2vtt/test/srt2vtt.spec.js' {
  declare module.exports: $Exports<'srt2vtt/test/srt2vtt.spec'>;
}
