// flow-typed signature: 7693e4de58eb2a4304e820f36d31d103
// flow-typed version: <<STUB>>/stylelint_v^7.6.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint/dist/assignDisabledRanges' {
  declare module.exports: any;
}

declare module 'stylelint/dist/augmentConfig' {
  declare module.exports: any;
}

declare module 'stylelint/dist/cli' {
  declare module.exports: any;
}

declare module 'stylelint/dist/createPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/dist/createStylelint' {
  declare module.exports: any;
}

declare module 'stylelint/dist/createStylelintResult' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/jsonFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/needlessDisablesStringFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/stringFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/verboseFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/getConfigForFile' {
  declare module.exports: any;
}

declare module 'stylelint/dist/getPostcssResult' {
  declare module.exports: any;
}

declare module 'stylelint/dist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/isPathIgnored' {
  declare module.exports: any;
}

declare module 'stylelint/dist/lintSource' {
  declare module.exports: any;
}

declare module 'stylelint/dist/needlessDisables' {
  declare module.exports: any;
}

declare module 'stylelint/dist/normalizeRuleSettings' {
  declare module.exports: any;
}

declare module 'stylelint/dist/postcssPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/dist/reference/keywordSets' {
  declare module.exports: any;
}

declare module 'stylelint/dist/reference/namedColorData' {
  declare module.exports: any;
}

declare module 'stylelint/dist/reference/propertySets' {
  declare module.exports: any;
}

declare module 'stylelint/dist/reference/punctuationSets' {
  declare module.exports: any;
}

declare module 'stylelint/dist/reference/shorthandData' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-name-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-name-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-name-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-semicolon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-no-empty/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-no-single-line/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-hex-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-hex-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-named/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-invalid-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-no-empty/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-word-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-media-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-property-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-property-no-outside-root/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-property-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-bang-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-bang-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-duplicate-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-ignored-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-redundant-longhand-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-properties-order/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-single-line-max-declarations/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-trailing-semicolon/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-no-important/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-property-unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-property-unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-property-value-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-property-value-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/font-family-name-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/font-family-no-duplicate-names/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/font-weight-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-calc-no-unspaced-operator/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-name-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-parentheses-newline-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-url-data-uris/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-url-no-scheme-relative/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-url-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-url-scheme-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-whitespace-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/indentation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/keyframe-declaration-no-important/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/length-zero-no-unit/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-line-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-nesting-depth/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-no-missing-punctuation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-range-operator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-range-operator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-browser-hacks/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-descending-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-duplicate-selectors/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-empty-source/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-eol-whitespace/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-extra-semicolons/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-indistinguishable-colors/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-invalid-double-slash-comments/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-missing-end-of-source-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-unknown-animations/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-unsupported-browser-features/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-leading-zero/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-max-precision/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-no-trailing-zeros/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/root-no-standard-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-non-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-brackets-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-operator-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-operator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-operator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-operator-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-attribute-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-class-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-combinator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-combinator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-descendant-combinator-no-non-space/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-id-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-max-compound-selectors/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-max-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-nested-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-attribute/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-combinator/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-empty/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-id/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-qualifying-type/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-type/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-universal/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-class-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-class-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-class-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-class-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-class-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-element-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-element-colon-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-element-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-root-no-composition/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-type-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-type-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/shorthand-property-no-redundant-values/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/string-no-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/string-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/stylelint-disable-reason/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/time-no-imperceptible/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-no-unknown/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-keyword-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/standalone' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/basicChecks' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/createRuleTester' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/mergeTestDescriptions' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/testRule' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/atRuleParamIndex' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/beforeBlockString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blockString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blurComments' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blurFunctionArguments' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blurInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/containsString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/declarationValueIndex' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/findAnimationName' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/findAtRuleContext' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/findFontFamily' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/findListStyleType' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/functionArgumentsSearch' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/getIsFileIgnored' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/getModulePath' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/getUnitFromValueNode' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasBlock' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasEmptyBlock' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasEmptyLine' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasLessInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasPsvInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/hasScssInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isAutoprefixable' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isCounterIncrementCustomIdentValue' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isCustomMediaQuery' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isCustomProperty' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isCustomPropertySet' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isKeyframeRule' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isKeyframeSelector' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isNumbery' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isOnlyWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isRangeContextMediaFeature' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxAtRule' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxDeclaration' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxFunction' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxMediaFeature' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxMediaFeatureName' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxProperty' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxRule' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxSelector' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxTypeSelector' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxUrl' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isStandardSyntaxValue' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isValidFontSize' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isValidHex' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isVariable' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/matchesStringOrRegExp' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/nextNonCommentNode' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/nodeContextLookup' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/optionsMatches' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/parseSelector' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/rawNodeString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/report' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/ruleMessages' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/validateObjectWithStringArrayProps' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/validateOptions' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/whitespaceChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint/dist/assignDisabledRanges.js' {
  declare module.exports: $Exports<'stylelint/dist/assignDisabledRanges'>;
}
declare module 'stylelint/dist/augmentConfig.js' {
  declare module.exports: $Exports<'stylelint/dist/augmentConfig'>;
}
declare module 'stylelint/dist/cli.js' {
  declare module.exports: $Exports<'stylelint/dist/cli'>;
}
declare module 'stylelint/dist/createPlugin.js' {
  declare module.exports: $Exports<'stylelint/dist/createPlugin'>;
}
declare module 'stylelint/dist/createStylelint.js' {
  declare module.exports: $Exports<'stylelint/dist/createStylelint'>;
}
declare module 'stylelint/dist/createStylelintResult.js' {
  declare module.exports: $Exports<'stylelint/dist/createStylelintResult'>;
}
declare module 'stylelint/dist/formatters/index.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/index'>;
}
declare module 'stylelint/dist/formatters/jsonFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/jsonFormatter'>;
}
declare module 'stylelint/dist/formatters/needlessDisablesStringFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/needlessDisablesStringFormatter'>;
}
declare module 'stylelint/dist/formatters/stringFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/stringFormatter'>;
}
declare module 'stylelint/dist/formatters/verboseFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/verboseFormatter'>;
}
declare module 'stylelint/dist/getConfigForFile.js' {
  declare module.exports: $Exports<'stylelint/dist/getConfigForFile'>;
}
declare module 'stylelint/dist/getPostcssResult.js' {
  declare module.exports: $Exports<'stylelint/dist/getPostcssResult'>;
}
declare module 'stylelint/dist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/index'>;
}
declare module 'stylelint/dist/isPathIgnored.js' {
  declare module.exports: $Exports<'stylelint/dist/isPathIgnored'>;
}
declare module 'stylelint/dist/lintSource.js' {
  declare module.exports: $Exports<'stylelint/dist/lintSource'>;
}
declare module 'stylelint/dist/needlessDisables.js' {
  declare module.exports: $Exports<'stylelint/dist/needlessDisables'>;
}
declare module 'stylelint/dist/normalizeRuleSettings.js' {
  declare module.exports: $Exports<'stylelint/dist/normalizeRuleSettings'>;
}
declare module 'stylelint/dist/postcssPlugin.js' {
  declare module.exports: $Exports<'stylelint/dist/postcssPlugin'>;
}
declare module 'stylelint/dist/reference/keywordSets.js' {
  declare module.exports: $Exports<'stylelint/dist/reference/keywordSets'>;
}
declare module 'stylelint/dist/reference/namedColorData.js' {
  declare module.exports: $Exports<'stylelint/dist/reference/namedColorData'>;
}
declare module 'stylelint/dist/reference/propertySets.js' {
  declare module.exports: $Exports<'stylelint/dist/reference/propertySets'>;
}
declare module 'stylelint/dist/reference/punctuationSets.js' {
  declare module.exports: $Exports<'stylelint/dist/reference/punctuationSets'>;
}
declare module 'stylelint/dist/reference/shorthandData.js' {
  declare module.exports: $Exports<'stylelint/dist/reference/shorthandData'>;
}
declare module 'stylelint/dist/rules/at-rule-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-blacklist/index'>;
}
declare module 'stylelint/dist/rules/at-rule-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/at-rule-name-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-name-case/index'>;
}
declare module 'stylelint/dist/rules/at-rule-name-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-name-newline-after/index'>;
}
declare module 'stylelint/dist/rules/at-rule-name-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-name-space-after/index'>;
}
declare module 'stylelint/dist/rules/at-rule-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/at-rule-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/at-rule-semicolon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-semicolon-newline-after/index'>;
}
declare module 'stylelint/dist/rules/at-rule-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-whitelist/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-newline-after/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-newline-before/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-space-after/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-space-before/index'>;
}
declare module 'stylelint/dist/rules/block-no-empty/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-no-empty/index'>;
}
declare module 'stylelint/dist/rules/block-no-single-line/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-no-single-line/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-newline-after/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-newline-before/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-space-after/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-space-before/index'>;
}
declare module 'stylelint/dist/rules/color-hex-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-hex-case/index'>;
}
declare module 'stylelint/dist/rules/color-hex-length/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-hex-length/index'>;
}
declare module 'stylelint/dist/rules/color-named/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-named/index'>;
}
declare module 'stylelint/dist/rules/color-no-hex/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-hex/index'>;
}
declare module 'stylelint/dist/rules/color-no-invalid-hex/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-invalid-hex/index'>;
}
declare module 'stylelint/dist/rules/comment-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/comment-no-empty/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-no-empty/index'>;
}
declare module 'stylelint/dist/rules/comment-whitespace-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-whitespace-inside/index'>;
}
declare module 'stylelint/dist/rules/comment-word-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-word-blacklist/index'>;
}
declare module 'stylelint/dist/rules/custom-media-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-media-pattern/index'>;
}
declare module 'stylelint/dist/rules/custom-property-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-property-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/custom-property-no-outside-root/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-property-no-outside-root/index'>;
}
declare module 'stylelint/dist/rules/custom-property-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-property-pattern/index'>;
}
declare module 'stylelint/dist/rules/declaration-bang-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-bang-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-bang-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-bang-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-duplicate-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-duplicate-properties/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-ignored-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-ignored-properties/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-redundant-longhand-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-redundant-longhand-properties/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-properties-order/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-properties-order/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-newline-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-newline-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-single-line-max-declarations/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-single-line-max-declarations/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-trailing-semicolon/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-trailing-semicolon/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-newline-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-no-important/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-no-important/index'>;
}
declare module 'stylelint/dist/rules/declaration-property-unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-property-unit-blacklist/index'>;
}
declare module 'stylelint/dist/rules/declaration-property-unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-property-unit-whitelist/index'>;
}
declare module 'stylelint/dist/rules/declaration-property-value-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-property-value-blacklist/index'>;
}
declare module 'stylelint/dist/rules/declaration-property-value-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-property-value-whitelist/index'>;
}
declare module 'stylelint/dist/rules/font-family-name-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/font-family-name-quotes/index'>;
}
declare module 'stylelint/dist/rules/font-family-no-duplicate-names/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/font-family-no-duplicate-names/index'>;
}
declare module 'stylelint/dist/rules/font-weight-notation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/font-weight-notation/index'>;
}
declare module 'stylelint/dist/rules/function-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-blacklist/index'>;
}
declare module 'stylelint/dist/rules/function-calc-no-unspaced-operator/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-calc-no-unspaced-operator/index'>;
}
declare module 'stylelint/dist/rules/function-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/function-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/function-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/function-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index'>;
}
declare module 'stylelint/dist/rules/function-max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-max-empty-lines/index'>;
}
declare module 'stylelint/dist/rules/function-name-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-name-case/index'>;
}
declare module 'stylelint/dist/rules/function-parentheses-newline-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-parentheses-newline-inside/index'>;
}
declare module 'stylelint/dist/rules/function-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-parentheses-space-inside/index'>;
}
declare module 'stylelint/dist/rules/function-url-data-uris/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-url-data-uris/index'>;
}
declare module 'stylelint/dist/rules/function-url-no-scheme-relative/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-url-no-scheme-relative/index'>;
}
declare module 'stylelint/dist/rules/function-url-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-url-quotes/index'>;
}
declare module 'stylelint/dist/rules/function-url-scheme-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-url-scheme-whitelist/index'>;
}
declare module 'stylelint/dist/rules/function-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-whitelist/index'>;
}
declare module 'stylelint/dist/rules/function-whitespace-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-whitespace-after/index'>;
}
declare module 'stylelint/dist/rules/indentation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/indentation/index'>;
}
declare module 'stylelint/dist/rules/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/index'>;
}
declare module 'stylelint/dist/rules/keyframe-declaration-no-important/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/keyframe-declaration-no-important/index'>;
}
declare module 'stylelint/dist/rules/length-zero-no-unit/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/length-zero-no-unit/index'>;
}
declare module 'stylelint/dist/rules/max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-empty-lines/index'>;
}
declare module 'stylelint/dist/rules/max-line-length/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-line-length/index'>;
}
declare module 'stylelint/dist/rules/max-nesting-depth/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-nesting-depth/index'>;
}
declare module 'stylelint/dist/rules/media-feature-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-colon-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-feature-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-colon-space-before/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-blacklist/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-case/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-whitelist/index'>;
}
declare module 'stylelint/dist/rules/media-feature-no-missing-punctuation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-no-missing-punctuation/index'>;
}
declare module 'stylelint/dist/rules/media-feature-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-parentheses-space-inside/index'>;
}
declare module 'stylelint/dist/rules/media-feature-range-operator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-range-operator-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-feature-range-operator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-range-operator-space-before/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/no-browser-hacks/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-browser-hacks/index'>;
}
declare module 'stylelint/dist/rules/no-descending-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-descending-specificity/index'>;
}
declare module 'stylelint/dist/rules/no-duplicate-selectors/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-duplicate-selectors/index'>;
}
declare module 'stylelint/dist/rules/no-empty-source/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-empty-source/index'>;
}
declare module 'stylelint/dist/rules/no-eol-whitespace/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-eol-whitespace/index'>;
}
declare module 'stylelint/dist/rules/no-extra-semicolons/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-extra-semicolons/index'>;
}
declare module 'stylelint/dist/rules/no-indistinguishable-colors/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-indistinguishable-colors/index'>;
}
declare module 'stylelint/dist/rules/no-invalid-double-slash-comments/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-invalid-double-slash-comments/index'>;
}
declare module 'stylelint/dist/rules/no-missing-end-of-source-newline/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-missing-end-of-source-newline/index'>;
}
declare module 'stylelint/dist/rules/no-unknown-animations/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-unknown-animations/index'>;
}
declare module 'stylelint/dist/rules/no-unsupported-browser-features/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-unsupported-browser-features/index'>;
}
declare module 'stylelint/dist/rules/number-leading-zero/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-leading-zero/index'>;
}
declare module 'stylelint/dist/rules/number-max-precision/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-max-precision/index'>;
}
declare module 'stylelint/dist/rules/number-no-trailing-zeros/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-no-trailing-zeros/index'>;
}
declare module 'stylelint/dist/rules/property-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-blacklist/index'>;
}
declare module 'stylelint/dist/rules/property-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-case/index'>;
}
declare module 'stylelint/dist/rules/property-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/property-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/property-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-whitelist/index'>;
}
declare module 'stylelint/dist/rules/root-no-standard-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/root-no-standard-properties/index'>;
}
declare module 'stylelint/dist/rules/rule-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-nested-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/rule-non-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-non-nested-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-brackets-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-brackets-space-inside/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-operator-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-operator-blacklist/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-operator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-operator-space-after/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-operator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-operator-space-before/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-operator-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-operator-whitelist/index'>;
}
declare module 'stylelint/dist/rules/selector-attribute-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-attribute-quotes/index'>;
}
declare module 'stylelint/dist/rules/selector-class-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-class-pattern/index'>;
}
declare module 'stylelint/dist/rules/selector-combinator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-combinator-space-after/index'>;
}
declare module 'stylelint/dist/rules/selector-combinator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-combinator-space-before/index'>;
}
declare module 'stylelint/dist/rules/selector-descendant-combinator-no-non-space/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-descendant-combinator-no-non-space/index'>;
}
declare module 'stylelint/dist/rules/selector-id-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-id-pattern/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/selector-max-compound-selectors/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-max-compound-selectors/index'>;
}
declare module 'stylelint/dist/rules/selector-max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-max-empty-lines/index'>;
}
declare module 'stylelint/dist/rules/selector-max-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-max-specificity/index'>;
}
declare module 'stylelint/dist/rules/selector-nested-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-nested-pattern/index'>;
}
declare module 'stylelint/dist/rules/selector-no-attribute/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-attribute/index'>;
}
declare module 'stylelint/dist/rules/selector-no-combinator/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-combinator/index'>;
}
declare module 'stylelint/dist/rules/selector-no-empty/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-empty/index'>;
}
declare module 'stylelint/dist/rules/selector-no-id/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-id/index'>;
}
declare module 'stylelint/dist/rules/selector-no-qualifying-type/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-qualifying-type/index'>;
}
declare module 'stylelint/dist/rules/selector-no-type/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-type/index'>;
}
declare module 'stylelint/dist/rules/selector-no-universal/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-universal/index'>;
}
declare module 'stylelint/dist/rules/selector-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-class-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-class-blacklist/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-class-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-class-case/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-class-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-class-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-class-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-class-parentheses-space-inside/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-class-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-class-whitelist/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-element-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-element-case/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-element-colon-notation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-element-colon-notation/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-element-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-element-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/selector-root-no-composition/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-root-no-composition/index'>;
}
declare module 'stylelint/dist/rules/selector-type-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-type-case/index'>;
}
declare module 'stylelint/dist/rules/selector-type-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-type-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/shorthand-property-no-redundant-values/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/shorthand-property-no-redundant-values/index'>;
}
declare module 'stylelint/dist/rules/string-no-newline/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/string-no-newline/index'>;
}
declare module 'stylelint/dist/rules/string-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/string-quotes/index'>;
}
declare module 'stylelint/dist/rules/stylelint-disable-reason/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/stylelint-disable-reason/index'>;
}
declare module 'stylelint/dist/rules/time-no-imperceptible/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/time-no-imperceptible/index'>;
}
declare module 'stylelint/dist/rules/unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-blacklist/index'>;
}
declare module 'stylelint/dist/rules/unit-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-case/index'>;
}
declare module 'stylelint/dist/rules/unit-no-unknown/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-no-unknown/index'>;
}
declare module 'stylelint/dist/rules/unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-whitelist/index'>;
}
declare module 'stylelint/dist/rules/value-keyword-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-keyword-case/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/value-list-max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-max-empty-lines/index'>;
}
declare module 'stylelint/dist/rules/value-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/standalone.js' {
  declare module.exports: $Exports<'stylelint/dist/standalone'>;
}
declare module 'stylelint/dist/testUtils/basicChecks.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/basicChecks'>;
}
declare module 'stylelint/dist/testUtils/createRuleTester.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/createRuleTester'>;
}
declare module 'stylelint/dist/testUtils/index.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/index'>;
}
declare module 'stylelint/dist/testUtils/mergeTestDescriptions.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/mergeTestDescriptions'>;
}
declare module 'stylelint/dist/testUtils/testRule.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/testRule'>;
}
declare module 'stylelint/dist/utils/atRuleParamIndex.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/atRuleParamIndex'>;
}
declare module 'stylelint/dist/utils/beforeBlockString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/beforeBlockString'>;
}
declare module 'stylelint/dist/utils/blockString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blockString'>;
}
declare module 'stylelint/dist/utils/blurComments.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blurComments'>;
}
declare module 'stylelint/dist/utils/blurFunctionArguments.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blurFunctionArguments'>;
}
declare module 'stylelint/dist/utils/blurInterpolation.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blurInterpolation'>;
}
declare module 'stylelint/dist/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/configurationError'>;
}
declare module 'stylelint/dist/utils/containsString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/containsString'>;
}
declare module 'stylelint/dist/utils/declarationValueIndex.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/declarationValueIndex'>;
}
declare module 'stylelint/dist/utils/findAnimationName.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/findAnimationName'>;
}
declare module 'stylelint/dist/utils/findAtRuleContext.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/findAtRuleContext'>;
}
declare module 'stylelint/dist/utils/findFontFamily.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/findFontFamily'>;
}
declare module 'stylelint/dist/utils/findListStyleType.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/findListStyleType'>;
}
declare module 'stylelint/dist/utils/functionArgumentsSearch.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/functionArgumentsSearch'>;
}
declare module 'stylelint/dist/utils/getIsFileIgnored.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/getIsFileIgnored'>;
}
declare module 'stylelint/dist/utils/getModulePath.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/getModulePath'>;
}
declare module 'stylelint/dist/utils/getUnitFromValueNode.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/getUnitFromValueNode'>;
}
declare module 'stylelint/dist/utils/hasBlock.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasBlock'>;
}
declare module 'stylelint/dist/utils/hasEmptyBlock.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasEmptyBlock'>;
}
declare module 'stylelint/dist/utils/hasEmptyLine.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasEmptyLine'>;
}
declare module 'stylelint/dist/utils/hasInterpolation.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasInterpolation'>;
}
declare module 'stylelint/dist/utils/hasLessInterpolation.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasLessInterpolation'>;
}
declare module 'stylelint/dist/utils/hasPsvInterpolation.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasPsvInterpolation'>;
}
declare module 'stylelint/dist/utils/hasScssInterpolation.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/hasScssInterpolation'>;
}
declare module 'stylelint/dist/utils/index.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/index'>;
}
declare module 'stylelint/dist/utils/isAutoprefixable.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isAutoprefixable'>;
}
declare module 'stylelint/dist/utils/isCounterIncrementCustomIdentValue.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isCounterIncrementCustomIdentValue'>;
}
declare module 'stylelint/dist/utils/isCustomMediaQuery.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isCustomMediaQuery'>;
}
declare module 'stylelint/dist/utils/isCustomProperty.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isCustomProperty'>;
}
declare module 'stylelint/dist/utils/isCustomPropertySet.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isCustomPropertySet'>;
}
declare module 'stylelint/dist/utils/isKeyframeRule.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isKeyframeRule'>;
}
declare module 'stylelint/dist/utils/isKeyframeSelector.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isKeyframeSelector'>;
}
declare module 'stylelint/dist/utils/isNumbery.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isNumbery'>;
}
declare module 'stylelint/dist/utils/isOnlyWhitespace.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isOnlyWhitespace'>;
}
declare module 'stylelint/dist/utils/isRangeContextMediaFeature.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isRangeContextMediaFeature'>;
}
declare module 'stylelint/dist/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isSingleLineString'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxAtRule.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxAtRule'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxDeclaration.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxDeclaration'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxFunction.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxFunction'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxMediaFeature.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxMediaFeature'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxMediaFeatureName.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxMediaFeatureName'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxProperty.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxProperty'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxRule.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxRule'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxSelector.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxSelector'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxTypeSelector.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxTypeSelector'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxUrl.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxUrl'>;
}
declare module 'stylelint/dist/utils/isStandardSyntaxValue.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isStandardSyntaxValue'>;
}
declare module 'stylelint/dist/utils/isValidFontSize.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isValidFontSize'>;
}
declare module 'stylelint/dist/utils/isValidHex.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isValidHex'>;
}
declare module 'stylelint/dist/utils/isVariable.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isVariable'>;
}
declare module 'stylelint/dist/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isWhitespace'>;
}
declare module 'stylelint/dist/utils/matchesStringOrRegExp.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/matchesStringOrRegExp'>;
}
declare module 'stylelint/dist/utils/nextNonCommentNode.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/nextNonCommentNode'>;
}
declare module 'stylelint/dist/utils/nodeContextLookup.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/nodeContextLookup'>;
}
declare module 'stylelint/dist/utils/optionsMatches.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/optionsMatches'>;
}
declare module 'stylelint/dist/utils/parseSelector.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/parseSelector'>;
}
declare module 'stylelint/dist/utils/rawNodeString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/rawNodeString'>;
}
declare module 'stylelint/dist/utils/report.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/report'>;
}
declare module 'stylelint/dist/utils/ruleMessages.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/ruleMessages'>;
}
declare module 'stylelint/dist/utils/validateObjectWithStringArrayProps.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/validateObjectWithStringArrayProps'>;
}
declare module 'stylelint/dist/utils/validateOptions.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/validateOptions'>;
}
declare module 'stylelint/dist/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/whitespaceChecker'>;
}
