// flow-typed signature: 2fbdfedf6f438f14cb0e7e583818af5f
// flow-typed version: <<STUB>>/super-kat_v^0.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'super-kat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'super-kat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'super-kat/browser' {
  declare module.exports: any;
}

declare module 'super-kat/lib/kat-api' {
  declare module.exports: any;
}

declare module 'super-kat/lib/Torrent' {
  declare module.exports: any;
}

declare module 'super-kat/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'super-kat/browser.js' {
  declare module.exports: $Exports<'super-kat/browser'>;
}
declare module 'super-kat/index' {
  declare module.exports: $Exports<'super-kat'>;
}
declare module 'super-kat/index.js' {
  declare module.exports: $Exports<'super-kat'>;
}
declare module 'super-kat/lib/kat-api.js' {
  declare module.exports: $Exports<'super-kat/lib/kat-api'>;
}
declare module 'super-kat/lib/Torrent.js' {
  declare module.exports: $Exports<'super-kat/lib/Torrent'>;
}
declare module 'super-kat/webpack.config.js' {
  declare module.exports: $Exports<'super-kat/webpack.config'>;
}
