// flow-typed signature: 72c97db8c0b3290452d78c90e30fd06d
// flow-typed version: <<STUB>>/trakt.tv_vgithub:amilajack/trakt.tv/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trakt.tv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'trakt.tv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'trakt.tv/index' {
  declare module.exports: $Exports<'trakt.tv'>;
}
declare module 'trakt.tv/index.js' {
  declare module.exports: $Exports<'trakt.tv'>;
}
