// flow-typed signature: 5d664890423104f03527661c058cb5d9
// flow-typed version: <<STUB>>/vlc-command_v^1.1.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vlc-command'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vlc-command' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vlc-command/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vlc-command/cmd.js' {
  declare module.exports: $Exports<'vlc-command/cmd'>;
}
declare module 'vlc-command/index' {
  declare module.exports: $Exports<'vlc-command'>;
}
declare module 'vlc-command/index.js' {
  declare module.exports: $Exports<'vlc-command'>;
}
