// flow-typed signature: 1c3037c5e4817784b0a56481b2af387c
// flow-typed version: <<STUB>>/webtorrent_vgithub:amilajack/webtorrent/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webtorrent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webtorrent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webtorrent/bin/test' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/file-stream' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/file' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/peer' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/rarity-map' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/server' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/tcp-pool' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/torrent' {
  declare module.exports: any;
}

declare module 'webtorrent/lib/webconn' {
  declare module.exports: any;
}

declare module 'webtorrent/test/browser/basic' {
  declare module.exports: any;
}

declare module 'webtorrent/test/client-add-duplicate-trackers' {
  declare module.exports: any;
}

declare module 'webtorrent/test/client-add' {
  declare module.exports: any;
}

declare module 'webtorrent/test/client-destroy' {
  declare module.exports: any;
}

declare module 'webtorrent/test/client-remove' {
  declare module.exports: any;
}

declare module 'webtorrent/test/client-seed' {
  declare module.exports: any;
}

declare module 'webtorrent/test/duplicate' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/basic' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/blocklist-dht' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/blocklist-tracker' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/blocklist' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-dht-magnet' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-dht-torrent' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-metadata' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-private-dht' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-tracker-magnet' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-tracker-torrent' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-webseed-magnet' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/download-webseed-torrent' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/extensions' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/metadata' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/seed-stream' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/seed-while-download' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/server' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/swarm-basic' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/swarm-reconnect' {
  declare module.exports: any;
}

declare module 'webtorrent/test/node/swarm-timeout' {
  declare module.exports: any;
}

declare module 'webtorrent/test/rarity-map' {
  declare module.exports: any;
}

declare module 'webtorrent/test/swarm' {
  declare module.exports: any;
}

declare module 'webtorrent/test/torrent-destroy' {
  declare module.exports: any;
}

declare module 'webtorrent/webtorrent.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webtorrent/bin/test.js' {
  declare module.exports: $Exports<'webtorrent/bin/test'>;
}
declare module 'webtorrent/index' {
  declare module.exports: $Exports<'webtorrent'>;
}
declare module 'webtorrent/index.js' {
  declare module.exports: $Exports<'webtorrent'>;
}
declare module 'webtorrent/lib/file-stream.js' {
  declare module.exports: $Exports<'webtorrent/lib/file-stream'>;
}
declare module 'webtorrent/lib/file.js' {
  declare module.exports: $Exports<'webtorrent/lib/file'>;
}
declare module 'webtorrent/lib/peer.js' {
  declare module.exports: $Exports<'webtorrent/lib/peer'>;
}
declare module 'webtorrent/lib/rarity-map.js' {
  declare module.exports: $Exports<'webtorrent/lib/rarity-map'>;
}
declare module 'webtorrent/lib/server.js' {
  declare module.exports: $Exports<'webtorrent/lib/server'>;
}
declare module 'webtorrent/lib/tcp-pool.js' {
  declare module.exports: $Exports<'webtorrent/lib/tcp-pool'>;
}
declare module 'webtorrent/lib/torrent.js' {
  declare module.exports: $Exports<'webtorrent/lib/torrent'>;
}
declare module 'webtorrent/lib/webconn.js' {
  declare module.exports: $Exports<'webtorrent/lib/webconn'>;
}
declare module 'webtorrent/test/browser/basic.js' {
  declare module.exports: $Exports<'webtorrent/test/browser/basic'>;
}
declare module 'webtorrent/test/client-add-duplicate-trackers.js' {
  declare module.exports: $Exports<'webtorrent/test/client-add-duplicate-trackers'>;
}
declare module 'webtorrent/test/client-add.js' {
  declare module.exports: $Exports<'webtorrent/test/client-add'>;
}
declare module 'webtorrent/test/client-destroy.js' {
  declare module.exports: $Exports<'webtorrent/test/client-destroy'>;
}
declare module 'webtorrent/test/client-remove.js' {
  declare module.exports: $Exports<'webtorrent/test/client-remove'>;
}
declare module 'webtorrent/test/client-seed.js' {
  declare module.exports: $Exports<'webtorrent/test/client-seed'>;
}
declare module 'webtorrent/test/duplicate.js' {
  declare module.exports: $Exports<'webtorrent/test/duplicate'>;
}
declare module 'webtorrent/test/node/basic.js' {
  declare module.exports: $Exports<'webtorrent/test/node/basic'>;
}
declare module 'webtorrent/test/node/blocklist-dht.js' {
  declare module.exports: $Exports<'webtorrent/test/node/blocklist-dht'>;
}
declare module 'webtorrent/test/node/blocklist-tracker.js' {
  declare module.exports: $Exports<'webtorrent/test/node/blocklist-tracker'>;
}
declare module 'webtorrent/test/node/blocklist.js' {
  declare module.exports: $Exports<'webtorrent/test/node/blocklist'>;
}
declare module 'webtorrent/test/node/download-dht-magnet.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-dht-magnet'>;
}
declare module 'webtorrent/test/node/download-dht-torrent.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-dht-torrent'>;
}
declare module 'webtorrent/test/node/download-metadata.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-metadata'>;
}
declare module 'webtorrent/test/node/download-private-dht.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-private-dht'>;
}
declare module 'webtorrent/test/node/download-tracker-magnet.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-tracker-magnet'>;
}
declare module 'webtorrent/test/node/download-tracker-torrent.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-tracker-torrent'>;
}
declare module 'webtorrent/test/node/download-webseed-magnet.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-webseed-magnet'>;
}
declare module 'webtorrent/test/node/download-webseed-torrent.js' {
  declare module.exports: $Exports<'webtorrent/test/node/download-webseed-torrent'>;
}
declare module 'webtorrent/test/node/extensions.js' {
  declare module.exports: $Exports<'webtorrent/test/node/extensions'>;
}
declare module 'webtorrent/test/node/metadata.js' {
  declare module.exports: $Exports<'webtorrent/test/node/metadata'>;
}
declare module 'webtorrent/test/node/seed-stream.js' {
  declare module.exports: $Exports<'webtorrent/test/node/seed-stream'>;
}
declare module 'webtorrent/test/node/seed-while-download.js' {
  declare module.exports: $Exports<'webtorrent/test/node/seed-while-download'>;
}
declare module 'webtorrent/test/node/server.js' {
  declare module.exports: $Exports<'webtorrent/test/node/server'>;
}
declare module 'webtorrent/test/node/swarm-basic.js' {
  declare module.exports: $Exports<'webtorrent/test/node/swarm-basic'>;
}
declare module 'webtorrent/test/node/swarm-reconnect.js' {
  declare module.exports: $Exports<'webtorrent/test/node/swarm-reconnect'>;
}
declare module 'webtorrent/test/node/swarm-timeout.js' {
  declare module.exports: $Exports<'webtorrent/test/node/swarm-timeout'>;
}
declare module 'webtorrent/test/rarity-map.js' {
  declare module.exports: $Exports<'webtorrent/test/rarity-map'>;
}
declare module 'webtorrent/test/swarm.js' {
  declare module.exports: $Exports<'webtorrent/test/swarm'>;
}
declare module 'webtorrent/test/torrent-destroy.js' {
  declare module.exports: $Exports<'webtorrent/test/torrent-destroy'>;
}
declare module 'webtorrent/webtorrent.min.js' {
  declare module.exports: $Exports<'webtorrent/webtorrent.min'>;
}
